export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const USER_POSITION_CHANGE = 'USER_POSITION_CHANGE';
export const MAP_REGION_CHANGE = 'MAP_REGION_CHANGE';
export const ENTER_AR = 'ENTER_AR';
export const LIST_NAV = 'LIST_NAV';
export const UPDATE_MARKERS = 'UPDATE_MARKERS';
<<<<<<< HEAD
export const UPDATE_MARKER_INDEX = 'UPDATE_MARKER_INDEX';
=======
export const CURRENT_DISPLAY_BADGE = 'CURRENT_DISPLAY_BADGE';
export const ARRAY_OF_COLLECTED_BADGES = 'ARRAY_OF_COLLECTED_BADGES';
export const ENTER_AR_TUTORIAL = 'ENTER_AR_TUTORIAL';
>>>>>>> b970f4fe5f14ef303a7322da4d9e5811f944ee8b
