source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'
target 'workingArgo' do
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'

  rn_path = '../node_modules/react-native'
  
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'BatchedBridge'
    ]
  
    pod 'react-native-maps', path: '../node_modules/react-native-maps'
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
    end
  end

# target 'FacebookPods' do
#   pod 'Bolts'
#   pod 'FBSDKCoreKit'
#   pod 'FBSDKShareKit'
#   pod 'FBSDKLoginKit'

#   target 'FacebookPodsTests' do
#     inherit! :search_paths
#   end
# end